### ISSUE TITLE
[Fix] 프로필 편집화면 관심 장르 없을때 separator 위치 수정 필요

### ISSUE THREAD

**Issue by JongHoooon** [SINZAK/sinzak-ios#139]
프로필 수정화면 관심 장르 없을때 separator 위치 수정 필요

<img src="https://github.com/SINZAK/sinzak-ios/assets/98168685/9f1cd85e-555d-4ea9-bd8c-aff2bbeef786" width="30%"> <img src="https://github.com/SINZAK/sinzak-ios/assets/98168685/f38e4de4-7c1d-413f-a547-561b56614dfe" width="30%">

**Comment by seungwon-yoo** [comment]
" "을 넣어서 해결하는 게 방법보다는 UI 자체를 수정하는 방법이 좋을 것 같습니다! 나중에 히스토리를 모르는 누군가가 봤을 땐 왜 이렇게 짰는지 모를 수 있어서요

**Comment by JongHoooon** [comment]
- #140
